# -*- coding: utf-8 -*-
"""M-Etrics Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_D_p5YuFOzxcHJV3fFoE1F7dQgVqskM0
"""



from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
df_tuition = pd.read_excel('tuition_cost.xlsx')
df_salaries = pd.read_excel('salaries-by-college-type.xlsx')
df_tuition.head()

def split_it(name):
  name_list = name.split("(")
  name_return = name_list[0].strip()
  return name_return
df_salaries['name_split'] = df_salaries['School Name'].apply(split_it)

df_salaries.sort_values('name_split', axis=0, inplace=True)
df_salaries.head()
df_joined = df_salaries.merge(df_tuition,left_on='name_split', right_on='name')
df_joined.head()

from sklearn import linear_model
import statsmodels.api as sm
import numpy as np

X = df_joined['out_of_state_total']
Y = df_joined['Mid-Career 75th Percentile Salary']
model = sm.OLS(Y,X).fit()


A = [df_joined['out_of_state_total'],df_joined['Mid-Career 25th Percentile Salary']]

print(b)

#In state